"""Create initial tables

Revision ID: e233625a9a0c
Revises: 
Create Date: 2024-09-17 23:01:35.454581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e233625a9a0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('imap_server', sa.String(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_services_id'), 'mail_services', ['id'], unique=False)
    op.create_index(op.f('ix_mail_services_name'), 'mail_services', ['name'], unique=True)
    op.create_table('mail_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['mail_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_accounts_id'), 'mail_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_mail_accounts_login'), 'mail_accounts', ['login'], unique=False)
    op.create_index(op.f('ix_mail_accounts_service_id'), 'mail_accounts', ['service_id'], unique=False)
    op.create_table('mail_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('mail_account_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('send_date', sa.DateTime(), nullable=False),
    sa.Column('receive_date', sa.DateTime(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('files', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mail_account_id'], ['mail_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_messages_id'), 'mail_messages', ['id'], unique=False)
    op.create_index(op.f('ix_mail_messages_message_id'), 'mail_messages', ['message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mail_messages_message_id'), table_name='mail_messages')
    op.drop_index(op.f('ix_mail_messages_id'), table_name='mail_messages')
    op.drop_table('mail_messages')
    op.drop_index(op.f('ix_mail_accounts_service_id'), table_name='mail_accounts')
    op.drop_index(op.f('ix_mail_accounts_login'), table_name='mail_accounts')
    op.drop_index(op.f('ix_mail_accounts_id'), table_name='mail_accounts')
    op.drop_table('mail_accounts')
    op.drop_index(op.f('ix_mail_services_name'), table_name='mail_services')
    op.drop_index(op.f('ix_mail_services_id'), table_name='mail_services')
    op.drop_table('mail_services')
    # ### end Alembic commands ###
